[reticulum]
  share_instance = True
  default_algorithm = curve25519
  tcp_port = 4321

[interfaces]
  [[TCP Server Interface]]
    type = TCPServerInterface
    enabled = yes
    listen_ip = 0.0.0.0
    listen_port = 37428

  [[TCP Client]]
    type = TCPClientInterface
    enabled = yes
    target_host = <redacted>
    target_port = 4965
